### ISSUE TITLE
Incorrect Calories

### ISSUE THREAD

**Issue by Puaaar** [brandonp2412/FitBook#45]
Upon update past and new added values get random increase in calories. Some things get counted correctly but others don't. Not exactly sure as to what the pattern is. Applies to existing foods and quick adds. 

Also the graphs for protein, carbohydrates, fat, and fiber seem to not be working. Fiber is a nice inclusion by the way. I also really like the new format with the day slider. 

I'm assuming this was an accidental push before finishing updates and you already know these problems but just in case I figured I'd say something. 

![Image](https://github.com/user-attachments/assets/ff7cbb92-1fa7-4c28-986a-621304618447)

![Image](https://github.com/user-attachments/assets/d0fcacb1-a163-43dc-95ed-891e5ff3071d)

![Image](https://github.com/user-attachments/assets/a21115ca-155e-4027-90bf-fed7b945f004)

![Image](https://github.com/user-attachments/assets/ab3ea92c-c1d4-49cc-8e9f-9b61b18f9324)

**Comment by brandonp2412** [comment]
When you say the other nutrients (not calories) are broken, what happens? Also if this is creating what looks like a crash, could you please try get the [adb logs](https://developer.android.com/tools/logcat) or email me [brandon@presley.nz](mailto:brandon@presley.nz) an export of your database so I can try re-produce it.

**Comment by Puaaar** [comment]
I don't think it is a crash but I should've screenshotted the graphs for the other macro-nutrients earlier. It's super weird but now the graphs are actually loading in data unlike before. It might have been because I was using the app immediately after the update to 1.0.105? Maybe graphs were still loading and initializing data? Re-reading what I reported I didn't explain it fully what was happening with the macro-nutrient graphs, it was simply that they just weren't displaying any data, it was just a blank space where the graph would be, but now the points are on the plot. However some of the days on the macro-nutrients graphs data is wrong just like with the calories. 

Anyways this was my first time using the Logcat command I think I used it correctly but I'm not entirely sure. Here's the result. If I did it wrong I can email you the export of my Diary, Foods, and Database if needed.

[fitbooklog.zip](https://github.com/user-attachments/files/18972828/fitbooklog.zip)

**Comment by brandonp2412** [comment]
Please test again with https://github.com/brandonp2412/FitBook/releases/tag/1.0.107 and close if it's fixed.

**Comment by Puaaar** [comment]
I just did the "app-arm64-v8a-release.apk" in specific on my phone and while it fixed the issue with how Quick-adds input calories actual Foods are still outputting the wrong calories both in the Diary section and in the Graph section. 

Also the removal of macro-nutrients on quick add for some reason caused the replacement of grams with calories. So when I would edit a quick add to include my guess of macro-nutrients and calories consumed it took what I would have put as: 
"100 grams, 1900 calories, 100 g protein, 40 g fat, 150 g carbohydrate"
and just kept the grams as calories on past quick-adds. So in this example in the version 1.0.107 instead of it being updated as 1900 calories with no macro-nutrients its just 100 calories.  

I will email you my database since it is not all foods that are outputting incorrect calories but only some. Of the ones I've identified from my database it is, "Wellsley Farms Black Forest Ham", and "Butter". Just in case it ends up in spam or something the email I will be sending from is allbeeliam@gmail.com

I think I could delete the Foods from the database and re enter them but losing all the past data of calories would mess up my cataloging of my calories.

**Comment by brandonp2412** [comment]
Are the wrong entries the ones made during the previous bugged version?

**Comment by Puaaar** [comment]
Technically the entries I made today are from the bugged version (1.0.105) yes but, there's also entries from every day before that that are affected by the bugged version but not made during the bugged version. For more context I eat the Black Forest Ham everyday so on my graphs and stuff every single day is affected.

**Comment by brandonp2412** [comment]
Do new entries from the 1.1.107 end up with wrong graphs as well? Might just be I missed a db migration

**Comment by Puaaar** [comment]
Yes new entries in 1.0.107 also produce the bugged outcome. Images attached show the result. I'm assuming its something that happens when parsing the data from the Entry to the Diary or Entry to the Graph or both. Because inside the individual food Entry in the Diary calories are correct but aren't translated correctly everywhere else.    

![Image](https://github.com/user-attachments/assets/80a7aa2f-c096-4df0-97d0-bc6309380616)

![Image](https://github.com/user-attachments/assets/f226be2f-e6bf-418f-990f-a2533ab55a38)

![Image](https://github.com/user-attachments/assets/8bf2b2fc-3a82-4a8c-a6fd-8a8ddfd62c14)

**Comment by Puaaar** [comment]
Though now that I think about it it's super bizarre that it only happens with some foods and not all of them if that was the case.

**Comment by Puaaar** [comment]
I think I just narrowed down some of the behavior of the bug. Something that I just noticed is that the bug is affecting Foods that have their default serving size as ounces. Any conversion from the default serving size seems to alter the calorie count in unexpected ways.

**Comment by Puaaar** [comment]
I've also just noticed Quick-adds seem to randomly add macro-nutrients. This might be based off a ratio from my last Quick-add before the 1.0.105 update when macro-nutrient data was available for Quick-adds. 

Image supplied is evidence. 

![Image](https://github.com/user-attachments/assets/b6c4ab85-0888-41d9-9ebc-4ab262f5a86b)

**Comment by brandonp2412** [comment]
OK there were a few issues here. I messed up saving & reading the serving sizes on foods so that i fixed first, and then some of the calculations on the entries list was wrong and that's fixed too. I'll push it shortly

**Comment by brandonp2412** [comment]
Please test https://github.com/brandonp2412/FitBook/releases/tag/1.0.108

**Comment by Puaaar** [comment]
Nice, 1.0.108 definitely fixes the main bug with the serving sizes and calculations. My graphs are definitely fixed now. An error still exists with the Quick-add feature. Should I close this and open a new issue just to keep everything organized? I also found a bug with the weight should I open a thread for that or continue here?

Thank you for your effort and quick response I appreciate it a lot 😄 💯

**Comment by brandonp2412** [comment]
Yep let's have different tickets for those thanks for the bug submission most people just uninstall if they see a bug haha

**Comment by LuigiBrosNin** [comment]
Thanks, can't wait for the f-droid update
